- Атрибуты

In [1]:
import numpy as np

In [2]:
arr_1 = np.random.randint(10, size = (3, 5))
arr_1

array([[9, 3, 1, 6, 0],
       [8, 3, 9, 8, 0],
       [4, 8, 2, 3, 1]])

In [3]:
# мерность массива(кол-во измерений/осей)
arr_1.ndim

2

In [4]:
# форма массива
arr_1.shape

(3, 5)

In [5]:
arr_1.shape[0]

3

In [6]:
# количество всех элементов массива
arr_1.size

15

In [7]:
# тип значений массива
arr_1.dtype

dtype('int32')

In [9]:
arr_2 = np.random.random(5)
arr_2.dtype

dtype('float64')

In [11]:
arr_2.astype("int8")

array([0, 0, 0, 0, 0], dtype=int8)

In [12]:
arr_1.astype("int8")

array([[9, 3, 1, 6, 0],
       [8, 3, 9, 8, 0],
       [4, 8, 2, 3, 1]], dtype=int8)

In [13]:
arr_1.astype("uint8")

array([[9, 3, 1, 6, 0],
       [8, 3, 9, 8, 0],
       [4, 8, 2, 3, 1]], dtype=uint8)

* Индексация

In [16]:
arr_3 = np.random.randint(10, size=10)
arr_3

array([1, 7, 5, 6, 8, 1, 9, 4, 9, 1])

In [17]:
arr_3[0]

1

In [19]:
arr_3[-1]

1

In [20]:
# индексация 2-мерных массивов
arr_4 = np.random.randint(10, size = (2, 3))
arr_4

array([[6, 2, 4],
       [4, 5, 7]])

In [21]:
# списковый синтаксис
arr_4[1][0]

4

In [22]:
# синтаксис numpy
arr_4[1][0]

4

- Срезы

In [23]:
arr_3[:5]

array([1, 7, 5, 6, 8])

In [24]:
arr_3[1:]

array([7, 5, 6, 8, 1, 9, 4, 9, 1])

In [25]:
arr_3[::-2]

array([1, 4, 1, 6, 7])

In [27]:
arr_4[0, 1:]

array([2, 4])

In [28]:
arr_4[:, :2]

array([[6, 2],
       [4, 5]])

- представления (views) и копии (copies)

In [30]:
# срез списка создает копию
# копия независима от исходного списка
my_list = [1, 2, 3, 4, 5]
my_list[2:]

[3, 4, 5]

In [32]:
sub_list = my_list[2:]
sub_list

[3, 4, 5]

In [33]:
sub_list[0] = 100
sub_list

[100, 4, 5]

In [34]:
my_list

[1, 2, 3, 4, 5]

In [35]:
# срез массива является представлением исходного массива
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

In [36]:
sub_array = my_array[2:]
sub_array

array([3, 4, 5])

In [37]:
sub_array[0] = 100
sub_array

array([100,   4,   5])

In [38]:
my_array

array([  1,   2, 100,   4,   5])

In [39]:
copy_array = my_array[2:].copy()
copy_array

array([100,   4,   5])

In [40]:
copy_array[0] = 10
copy_array

array([10,  4,  5])

In [41]:
my_array

array([  1,   2, 100,   4,   5])

- Изменение формы

In [42]:
# 1-мерный массив (вектор-строка)
arr_5 = np.arange(1, 10)
arr_5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr_5.shape

(9,)

In [44]:
# вектор столбец 
# технически получается 2-мерный массив
arr_5.reshape((9, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## Операции
- Универсальные функции

In [45]:
a = np.arange(5)
b = np.arange(2, 7)
print(a)
print(b)

[0 1 2 3 4]
[2 3 4 5 6]


In [46]:
# по элементное сложение массивов
# "+" - это алиас универсальной функции np.add()
a + b

array([ 2,  4,  6,  8, 10])

In [47]:
np.add(a, b)

array([ 2,  4,  6,  8, 10])

In [50]:
np.add(10, 20)

30

In [52]:
x = np.arange(3)
x

array([0, 1, 2])

In [53]:
#обычное (поэлементное) умножение (результат - произведение Адамара)
x * x

array([0, 1, 4])

In [54]:
# матричное умножение
x1 = x.reshape((3, 1))
x1

array([[0],
       [1],
       [2]])

In [55]:
np.dot(x, x1)

array([5])

In [56]:
# x[0] * x1[0] + x[1] * x1[1] + x[2] * x1[2]

In [58]:
y = np.arange(6).reshape((2, 3))
y

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
# транспонирование
y1 = y.T
y1

array([[0, 3],
       [1, 4],
       [2, 5]])

In [60]:
np.dot(y, y1)

array([[ 5, 14],
       [14, 50]])

In [61]:
# Линейная алгебра - самостоятельно