In [1]:
import numpy as np

* агрегирование

Агрегирование - вычисление неких сводных показателей.

In [2]:
arr_1 = np.random.random(10)
arr_1

array([0.12602011, 0.79397233, 0.70253211, 0.28288107, 0.49237543,
       0.43742289, 0.40153757, 0.87838806, 0.34325114, 0.31359525])

In [3]:
# сумма
# 1D-array
np.sum(arr_1)

4.771975956085101

In [4]:
# 2D - array
np.sum(arr_1.reshape((2, 5)))

4.771975956085101

In [5]:
# минимум
np.min(arr_1)

0.12602010743601177

In [6]:
# максимум
np.max(arr_1)

0.878388059784578

In [7]:
# среднее арифметическое 
np.mean(arr_1)

0.4771975956085101

- сравнения

In [8]:
arr_2 = np.arange(5)
arr_2

array([0, 1, 2, 3, 4])

In [9]:
arr_2 != 2

array([ True,  True, False,  True,  True])

In [10]:
arr_2 == 2

array([False, False,  True, False, False])

In [12]:
np.arange(10).reshape((5, 2)) >= 2

array([[False, False],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [13]:
# общее сравнение 
# имеются ли в массиве какие-либо значения, отвечающие условию
np.any(arr_2 > 3)

True

In [14]:
# все ли значения отвечают условию
np.all(arr_2 < 2)

False

In [15]:
arr_3 = np.arange(10).reshape((5, 2))
arr_3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
c = arr_3 > 5
c

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [18]:
np.any(c, axis = 0)

array([ True,  True])

In [19]:
np.any(c, axis = 1)

array([False, False, False,  True,  True])

- маскирование

In [20]:
arr_4 = np.random.randint(10, size = 5)
arr_4

array([0, 1, 7, 0, 3])

In [22]:
# массив из булевых значений - маска
c = arr_4 < 3
c

array([ True,  True, False,  True, False])

In [26]:
# операция маскирование
a = arr_4[c]
a

array([0, 1, 0])

In [27]:
arr_4[arr_4 != 2]

array([0, 1, 7, 0, 3])

In [29]:
arr_5 = np.random.randint(10, size=(3,3))
arr_5

array([[9, 7, 5],
       [0, 1, 7],
       [1, 5, 0]])

In [30]:
arr_6 = np.arange(9)
arr_6

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

- прихотливая индексация (fancy indieces)

In [33]:
arr_5 = np.arange(10, 20)
arr_5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
# с помощью списка
arr_5[[3, 0, 5]]

array([13, 10, 15])

In [37]:
# спомощью массива
fi = np.random.randint(len(arr_5), size = 4)
fi

array([5, 2, 9, 4])

In [39]:
arr_5[fi]

array([15, 12, 19, 14])

In [41]:
# прихотливая индексация может менять форму
fi = np.array([[3,0,1],[1,1,5]])
fi

array([[3, 0, 1],
       [1, 1, 5]])

In [42]:
arr_5[fi]

array([[13, 10, 11],
       [11, 11, 15]])